import type { INodeProperties } from 'n8n-workflow';

export const projectFieldsCollection: INodeProperties = {
	displayName: 'Fields',
	name: 'fields',
	type: 'collection',
	typeOptions: {
		multipleValueButtonText: 'Add Field',
	},
	default: {},
	options: [
		{
			displayName: 'Address',
			name: 'address',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'address' } },
		},
		{
			displayName: 'Assigned Role URL',
			name: 'assignedRole',
			type: 'string',
			default: '',
			placeholder: 'https://api.opensolar.com/api/orgs/1/roles/123/',
			routing: { send: { type: 'body', property: 'assigned_role' } },
		},
		{
			displayName: 'Country ISO2',
			name: 'countryIso2',
			type: 'string',
			default: '',
			placeholder: 'e.g. AU',
			description: 'ISO 3166-1 alpha-2 country code',
			routing: { send: { type: 'body', property: 'country_iso2' } },
		},
		{
			displayName: 'Identifier',
			name: 'identifier',
			type: 'string',
			default: '',
			description: 'External identifier for the project, e.g. a CRM record ID',
			routing: { send: { type: 'body', property: 'identifier' } },
		},
		{
			displayName: 'Is Residential',
			name: 'isResidential',
			type: 'boolean',
			default: true,
			routing: { send: { type: 'body', property: 'is_residential' } },
		},
		{
			displayName: 'Latitude',
			name: 'lat',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'lat' } },
		},
		{
			displayName: 'Lead Source',
			name: 'leadSource',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'lead_source' } },
		},
		{
			displayName: 'Locality',
			name: 'locality',
			type: 'string',
			default: '',
			description: 'City or suburb',
			routing: { send: { type: 'body', property: 'locality' } },
		},
		{
			displayName: 'Longitude',
			name: 'lon',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'lon' } },
		},
		{
			displayName: 'Notes',
			name: 'notes',
			type: 'string',
			typeOptions: { rows: 3 },
			default: '',
			routing: { send: { type: 'body', property: 'notes' } },
		},
		{
			displayName: 'Number of Phases',
			name: 'numberOfPhases',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'number_of_phases' } },
		},
		{
			displayName: 'Roof Type URL',
			name: 'roofType',
			type: 'string',
			default: '',
			placeholder: 'https://api.opensolar.com/api/roof_types/6/',
			description: 'See docs/opensolar-api/roof-types.md for the available roof type IDs',
			routing: { send: { type: 'body', property: 'roof_type' } },
		},
		{
			displayName: 'State',
			name: 'state',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'state' } },
		},
		{
			displayName: 'Zip',
			name: 'zip',
			type: 'string',
			default: '',
			routing: { send: { type: 'body', property: 'zip' } },
		},
	],
};
